### ISSUE TITLE
Failed to use command `nvidia-smi`

### ISSUE THREAD

**Issue by johnny12150** [brokeDude2901/dxgkrnl_ubuntu#1]
- Host OS: Win10 H2
- Guest OS (VM OS): Ubuntu 20.04 
- GPU driver: 516.40

I have followed the instruction to execute all commands without encountering any errors.
However, I am not able to use `nvida-smi`.
By the way, `nvidia-smi` works in my WSL2 with Ubuntu 20.04.

More info:
```
$ uname -r
5.15.0-41-generic
```

```
$ lspci
be44:00:00.0 3D controller: Microsoft Corporation Device 008e
```

Full error log:
```
Failed to initialize NVML: GPU access blocked by the operating system 
Failed to properly shut down NVML: GPU access blocked by the operating system 
```

**Comment by johnny12150** [comment]
![image](https://user-images.githubusercontent.com/22369387/181774188-9ccad567-9bbc-4ad3-95cc-d58220b8ef9b.png)

It seems that the GPU has been detected but `nvidia-smi` command can't be executed.

**Comment by brokeDude2901** [comment]
hi you need to install dxgkrnl kernel from the release page and set it to boot as default option
`cd ~/
wget https://github.com/brokeDude2901/dxgkrnl_ubuntu/releases/download/main/linux-headers-5.10.102.1-dxgrknl_5.10.102.1-dxgrknl-10.00.Custom_amd64.deb
wget https://github.com/brokeDude2901/dxgkrnl_ubuntu/releases/download/main/linux-image-5.10.102.1-dxgrknl_5.10.102.1-dxgrknl-10.00.Custom_amd64.deb
sudo dpkg -i *.deb`

**Comment by johnny12150** [comment]
Thanks, I have the issue by selecting correct kernel under the grub menu.
